"""The MCP tool catalog — the agent-facing prompt copy, separated from the wiring.

`_CATALOG` is the registry of `(group, name, fn, description, json_schema)` tuples
that the MCP server advertises to a coding agent; the descriptions and schemas here
are effectively prompt text the agent reads, so they're worth keeping in one place
apart from the ~50 thin tool implementations (those live in `mcp_tools`).

**Names are domain-namespaced** (`<domain>_<verb>_<object>`) so an agent can route
to the right tool from the *name alone*, without paying a schema fetch — the name is
the only zero-token signal under deferred (name-only) tool loading. The domains:
`proj` (projects) · `target` (target lifecycle + every target-creator, incl. rehost)
· `re` (static reverse engineering) · `fs` (a target's unpacked filesystem) · `obs`
(the Observation store) · `graph` (the curated node/edge/hypothesis graph) · `finding`
(findings, n-day, proving) · `src` (source trees + builds) · `fuzz` (campaigns) ·
`net` (live network interaction + egress) · `task` (the task runner) · `meta`
(schemas + health). The advertised *name* is what changed; the underlying `mcp_tools`
functions keep their original names.

**Closed value-sets are real `enum`s, sourced from the codebase's own definitions**
(`NodeType`/`EdgeType`/`SOCKET_KINDS`/annotation kinds/Finding Literals/…), so the
agent can't pass a node/edge/finding type the engine doesn't understand, and the lists
never drift from `meta_get_schemas` — adding a `NodeType` member updates both at once
(the String columns keep zero-migration; the enum just mirrors the current vocab).

The dependency is strictly one-way: this module imports the tool functions from
`mcp_tools`; `mcp_tools` re-exports `GROUPS`/`catalog` from here for back-compat, but
never the other way around — so there is no import cycle.
"""

from __future__ import annotations

import typing as _typing

from hexgraph.db.models import EdgeType, FindingStatus, NodeType
from hexgraph.agent import mcp_tools as _t
from hexgraph.agent.agent_tools import MAX_CHARS_DESC as _MAX_CHARS_DESC
from hexgraph.engine.findings.assurance import PRECONDITIONS as _PRECONDITIONS
from hexgraph.engine.graph.annotations import KINDS as _ANN_KINDS, NODE_KINDS as _ANN_NODE_KINDS
from hexgraph.engine.build.build import BUILD_SYSTEMS as _BUILD_SYSTEMS
from hexgraph.engine.graph.edge_schemas import SOCKET_KINDS as _SOCKET_KINDS
from hexgraph.engine.findings.findings import FINDING_TYPES as _FINDING_TYPES
from hexgraph.engine.fuzzers.base import SURFACE_ENGINES as _SURFACE_ENGINES, SURFACES as _FUZZ_SURFACES
from hexgraph.engine.graph.hypotheses import (
    RELATIONS as _RELATIONS,
    STATUSES as _HYP_STATUSES,
    WORK_STATES as _HYP_WORK_STATES,
)
from hexgraph.engine.journal import AUTHORS as _JOURNAL_AUTHORS
from hexgraph.engine.llm_tasks import LLM_TASK_TYPES as _LLM_TASK_TYPES
from hexgraph.models.finding import Finding as _Finding

# --- Canonical closed value-sets (the SAME sources meta_get_schemas reads) ---------
# Generated from the codebase so the schema enum can never drift from the engine's
# vocab. A developer adding a NodeType/EdgeType member updates both places at once.
NODE_TYPES = [t.value for t in NodeType if t != NodeType.task]
EDGE_TYPES = [t.value for t in EdgeType]
SOCKET_KIND_VALUES = list(_SOCKET_KINDS)
ANNOTATION_KINDS = sorted(_ANN_KINDS)
ANNOTATION_NODE_KINDS = sorted(_ANN_NODE_KINDS)
FINDING_TYPE_VALUES = list(_FINDING_TYPES)
FINDING_STATUSES = [s.value for s in FindingStatus]
SEVERITIES = list(_typing.get_args(_Finding.model_fields["severity"].annotation))
CONFIDENCES = list(_typing.get_args(_Finding.model_fields["confidence"].annotation))
CATEGORIES = list(_typing.get_args(_Finding.model_fields["category"].annotation))

# run_task types: the LLM task set is canonical (engine.llm_tasks.LLM_TASK_TYPES); the
# deterministic types mirror engine.worker dispatch (no single constant for those).
TASK_TYPES = sorted(
    set(_LLM_TASK_TYPES) | {"recon", "fuzzing", "poc", "surface_recon", "web_recon", "web_discover"}
)

# Closed sets whose authority is not a single importable constant — listed here next to
# a pointer to the code that enforces them, so the schema documents the real allowlist.
REMOTE_TOOLS = ["uname", "id", "ps", "netstat", "mount", "ifconfig", "df", "env",
                "passwd", "release", "processes_full",  # = sandbox/probes/remote_probe.py:TOOLS keys
                "ls"]  # + the `ls` op (mcp_tools.remote_run maps tool='ls' → the read-only ls op)
REHOST_BRANDS = ["linksys", "netgear", "dlink", "tplink", "tenda", "trendnet", "zyxel",
                 "belkin", "asus", "mikrotik", "ubiquiti", "openwrt", "ddwrt", "buffalo",
                 "actiontec"]  # engine/targets/rehost.py:_VENDOR_BRANDS (FirmAE vendor profiles)
LLM_BACKENDS = ["mock", "anthropic", "claude_code"]  # llm backend registry
SOURCE_ROLES = ["code", "harness", "poc", "script", "build_recipe"]
BUILD_SYSTEMS = list(_BUILD_SYSTEMS)  # engine/build/build.py:BUILD_SYSTEMS
FUZZ_SURFACES = list(_FUZZ_SURFACES)  # engine/fuzzers/base.py:SURFACES
FUZZ_ENGINES = sorted({e for es in _SURFACE_ENGINES.values() for e in es})  # engine/fuzzers/base.py:SURFACE_ENGINES
EVIDENCE_RELATIONS = sorted(_RELATIONS)  # engine.graph.hypotheses.RELATIONS: supports/refutes + confirms/contradicts aliases
HYPOTHESIS_STATUSES = list(_HYP_STATUSES)  # engine.graph.hypotheses.STATUSES: derived (open/supported/refuted/contested) + verdicts
JOURNAL_AUTHORS = list(_JOURNAL_AUTHORS)  # engine.journal.AUTHORS: human | agent
HYPOTHESIS_WORK_STATES = list(_HYP_WORK_STATES)  # engine.graph.hypotheses.WORK_STATES: investigating/parked/done (the worklist axis)
REACHABILITY_PRECONDITIONS = list(_PRECONDITIONS)  # engine.findings.assurance.PRECONDITIONS: unauthenticated/requires_credentials/unspecified

# Tool groups let a user expose only what they need so an agent's context isn't
# polluted with tools they won't use:
#   read  — inspect the graph / target (no side effects)
#   write — populate the graph (findings, nodes, edges, hypotheses, annotations)
#   run   — execute HexGraph tasks in the sandbox (recon/analysis/fuzz)
GROUPS = ("read", "write", "run")

_CATALOG = [
    # ---- proj: projects -------------------------------------------------------------
    ("read", "proj_list", _t.list_projects, "List HexGraph projects (id, name, backend) — start here to find the project_id other tools need.",
     {"type": "object", "properties": {}}),
    ("write", "proj_create", _t.create_project, "Create a new EMPTY project (no target required) and return {id, name, backend} — the source-first entry point. target_ingest only makes a project alongside a binary/firmware path, so a pure source/fuzzing workflow (src_import_tree → src_build → fuzz_start) starts here, then feeds the returned id to those tools. `backend` is the LLM backend (defaults to mock).",
     {"type": "object", "properties": {"name": {"type": "string", "description": "project display name"}, "backend": {"type": "string", "enum": LLM_BACKENDS, "description": "LLM backend (default mock — zero token spend)"}}, "required": ["name"]}),
    ("read", "proj_doctor", _t.doctor, "RECONCILE the on-disk project dirs (under HEXGRAPH_HOME/projects/) against the DB and report drift: orphan dirs (a directory with no matching DB project — a removed/relocated/half-finished ingest) and DB projects whose dir is missing. Read-only report by default; pass clean=true to DELETE the orphan DIRS (reclaims stale bytes — never removes a DB project, which goes only through the explicit delete path). Use when proj_list and the on-disk project count disagree.",
     {"type": "object", "properties": {"clean": {"type": "boolean", "description": "delete orphan project dirs (default false = report only)"}}}),

    # ---- target: target lifecycle + every target-creator (incl. rehost) -------------
    ("read", "target_list", _t.list_targets, "List the VISIBLE targets in a project (binaries, libraries, REVEALED firmware children, web_app surfaces) with id/kind/arch/visible — the entry point for picking what to analyze. A firmware's ELF children are HIDDEN by default (unpack registers them so they're searchable/addressable, but they don't flood the graph); pass include_hidden=true to enumerate them too, then target_set_visible / target_reveal_dir to bring the interesting ones into the graph.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "include_hidden": {"type": "boolean", "description": "also list hidden firmware children (default false)"}}, "required": ["project_id"]}),
    ("read", "target_facts", _t.target_facts, "The cached recon SUMMARY for a target — its detected architecture and file format, the key imported/exported symbols, and the security mitigations recon already computed at ingest. The cheapest first orientation (it reads stored recon, no sandbox run). Note its `dangerous_imports` to find the risky libc calls fast. For the AUTHORITATIVE, uncapped symbol table + relocations + full mitigations, run re_binutils_facts instead.",
     {"type": "object", "properties": {"target_id": {"type": "string"}}, "required": ["target_id"]}),
    ("run", "target_ingest", _t.ingest, "INGEST a binary/firmware from a local path as a new target (the bytes are processed in the sandbox; firmware unpacks into child targets). Use this to bring a binary/firmware artifact into HexGraph. Creates a project if none is given. Returns a BOUNDED summary — {root_target_id, children_count, a preview of the first ~20 children, format}; call target_list(project_id) for the FULL child set (firmware can unpack into hundreds).",
     {"type": "object", "properties": {"path": {"type": "string", "description": "local filesystem path to the binary/firmware"}, "name": {"type": "string", "description": "optional target name (defaults from the path)"}, "project_id": {"type": "string", "description": "optional; a NEW project is created if omitted"}}, "required": ["path"]}),
    ("run", "target_promote_file", _t.promote_file, "PROMOTE one file from a firmware target's unpacked filesystem into its OWN child target — the bridge from browsing the rootfs (fs_list/fs_read_file) to ANALYZING a binary in it (re_decompile_function/re_list_functions/task_run/fuzz_start). `path` is relative to the extracted root; an entry's `is_elf` flags a binary worth promoting, `added` means it's already a target. Runs recon in the sandbox when Docker is up; idempotent per path. Use when fs_list surfaces an interesting binary (a CGI, a service daemon, a helper) that unpack didn't already register. Promoting a CONTAINER (.pkg/squashfs/cpio — e.g. a Cisco IOS-XE package) extracts it and registers its inner binaries as HIDDEN child targets; the result then reports `registered_children` (+ a note: target_list(include_hidden=true) to see them, target_set_visible to analyze one) and `packed_containers` for any still-nested containers. Returns {id, name, kind, parent_id, arch, registered_children?, packed_containers?, note?}.",
     {"type": "object", "properties": {"target_id": {"type": "string", "description": "the firmware target whose filesystem holds the file"}, "path": {"type": "string", "description": "file path relative to the extracted root (see fs_list)"}}, "required": ["target_id", "path"]}),
    ("run", "target_register_web_surface", _t.register_web_surface, "REGISTER a live WEB attack surface (a web_app target via an HTTP Channel, no bytes) — for a base URL you already have. Pass an optional offline route spec, then task_run(surface_recon) to map endpoints/params + routes_to→handler edges. Offline (no egress) to register; assessing it needs features.network.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "base_url": {"type": "string", "description": "the surface's base URL (loopback/private host)"}, "name": {"type": "string", "description": "optional surface name"}, "endpoints": {"type": "array", "description": "optional offline route spec [{path, method?, params?}] to seed endpoint/param nodes"}}, "required": ["project_id", "base_url"]}),
    ("run", "target_register_service", _t.register_service, "REGISTER a bare NON-HTTP network service (a live raw TCP/UDP listener) as a `service` target — a bind shell, vendor binary protocol, or custom daemon that already exists. No bytes, NO credentials (don't misuse target_register_remote(transport=telnet) for this — that carries SSH/telnet shell semantics a bare protocol endpoint doesn't have). Then fuzz_start infers the `network` surface and fuzzes this host:port (boofuzz), and net_tcp_request/finding_verify_poc probe+prove it. Bounded local-network tier: loopback/private only, audited. Gated: features.network.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "host": {"type": "string", "description": "service host (loopback/private only)"}, "port": {"type": "integer", "description": "service port"}, "name": {"type": "string", "description": "optional service name"}, "transport": {"type": "string", "enum": ["tcp", "udp"], "description": "transport (default tcp)"}, "proto": {"type": "string", "description": "optional free-form protocol label (e.g. 'http-like', 'custom-tlv')"}, "parent_ref": {"type": "string", "description": "optional parent target id (e.g. a rehosted firmware) so the probe reaches the device's private IP via the emulator netns"}}, "required": ["project_id", "host", "port"]}),
    ("run", "target_register_remote", _t.register_remote, "REGISTER a live REMOTE device (a physical box or a rehosted device) as a `remote` target reached over SSH/telnet — then analyze it read-only with net_remote_list_files/net_remote_read_file/net_remote_run. Creds come from operator env/config (HEXGRAPH_REMOTE_PASSWORD/KEY or config.toml [remote]), NEVER stored. Gated: features.remote.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "host": {"type": "string", "description": "device host/IP"}, "port": {"type": "integer", "description": "SSH/telnet port (default per transport)"}, "username": {"type": "string", "description": "login user (credential value comes from env/config, never here)"}, "transport": {"type": "string", "enum": ["ssh", "telnet"], "description": "transport (default ssh)"}, "name": {"type": "string", "description": "optional target name"}}, "required": ["project_id", "host"]}),
    ("run", "target_rehost", _t.rehost, "REHOST a FIRMWARE target — boot it under full-system emulation (auto-selects qemu+KVM for a full-OS disk image .vmdk/.qcow2/partitioned .img, or FirmAE for a vendor blob squashfs/cramfs/…) and register its live web server as a web_app surface CHILD target, then assess the running device with task_run(surface_recon/web_discover)/net_http_request/finding_verify_poc, fused to the firmware's static graph. For a FirmAE/vendor image, pass `brand` if it reports it couldn't bring up the network (FirmAE's profile is vendor-keyed; auto-inferred when the firmware names its vendor). Heavy + best-effort. Gated: features.rehost (boot) + features.network (assess).",
     {"type": "object", "properties": {"target_id": {"type": "string", "description": "the firmware target to boot"}, "brand": {"type": "string", "enum": REHOST_BRANDS, "description": "FirmAE vendor profile (auto-inferred from firmware strings when omitted)"}}, "required": ["target_id"]}),
    ("write", "target_archive", _t.archive_target, "Soft-remove a target + its whole subtree (children/nodes/findings) from the graph (REVERSIBLE) — declutter an irrelevant component; re-ingesting the bytes or target_restore brings it back. (Whole-project deletion is operator-only, not an MCP tool.)",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "target_id": {"type": "string"}}, "required": ["project_id", "target_id"]}),
    ("write", "target_restore", _t.restore_target, "Un-archive a previously soft-removed target subtree (its nodes/findings reappear).",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "target_id": {"type": "string"}}, "required": ["project_id", "target_id"]}),
    ("write", "target_set_visible", _t.set_visible, "REVEAL (visible=true) or re-HIDE (visible=false) ONE target in the curated graph. Firmware ELF children are hidden by default — unpack registers each (searchable via target_list(include_hidden=true), addressable, recon-enriched) but they'd flood the graph, so they contribute NOTHING to it until revealed. Revealing materializes the target's recon symbol/string nodes from the already-stored facts (no re-run), so it joins the graph + Targets pane. Use after target_list(include_hidden=true)/fs_list surfaces a child worth analyzing. Returns {target_id, name, visible, materialized}.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "target_id": {"type": "string"}, "visible": {"type": "boolean", "description": "true to reveal (default), false to re-hide"}}, "required": ["project_id", "target_id"]}),
    ("write", "target_reveal_dir", _t.reveal_dir, "REVEAL every HIDDEN child of a firmware whose rootfs path is under `prefix` (e.g. prefix='usr/sbin' reveals all ELFs in /usr/sbin) — the bulk counterpart to target_set_visible for bringing a whole directory of binaries into the curated graph at once. An empty prefix reveals ALL hidden children. Materializes each revealed child's recon nodes from stored facts (no re-run). `target_id` is the firmware. Returns {firmware_target_id, prefix, revealed, target_ids}.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "target_id": {"type": "string", "description": "the firmware target whose children to reveal"}, "prefix": {"type": "string", "description": "rootfs directory prefix (e.g. 'usr/sbin'); empty reveals all hidden children"}}, "required": ["project_id", "target_id"]}),

    # ---- re: static reverse engineering ---------------------------------------------
    ("read", "re_list_functions", _t.list_functions, "List the functions in a target (name + address), discovered in the sandbox — use to find what to decompile next. QUERY: returns results and records an Observation; does NOT add graph nodes — review and promote what matters (re_decompile_function promotes one). Check obs_list(target_id) first to avoid re-running.",
     {"type": "object", "properties": {"target_id": {"type": "string"}}, "required": ["target_id"]}),
    ("read", "re_decompile_function", _t.decompile_function, "Decompile one function to pseudo-C in the sandbox (radare2/Ghidra) — the primary way to read a target's logic without touching its bytes. PROMOTE: deliberately adds THIS function to the curated graph (enriched in place with its recovered prototype/address) and draws `calls` edges only to callees ALREADY in the graph; new callees are listed for optional promotion, never auto-added (no fan-out). Also records an Observation. A long function is truncated to max_chars with a marker naming both recovery paths (re-call with a bigger max_chars, or obs_get for the full body).",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "function": {"type": "string", "description": "function name (see re_list_functions)"}, "max_chars": {"type": "integer", "description": _MAX_CHARS_DESC}}, "required": ["target_id", "function"]}),
    ("read", "re_decompile_at", _t.decompile_at, "Decompile the function CONTAINING a hex ADDRESS (e.g. 0x401200) in the sandbox — analyze-at-address for when you have an address (from re_xrefs/strings/a crash backtrace) but not a function name. PROMOTE: same as re_decompile_function for the resolved function (adds it to the graph, `calls` edges only to already-curated callees, new callees listed not auto-added). Records an Observation. A long function is truncated to max_chars with a marker naming both recovery paths (re-call with a bigger max_chars, or obs_get for the full body).",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "address": {"type": "string", "description": "hex address inside the function, e.g. 0x401200"}, "max_chars": {"type": "integer", "description": _MAX_CHARS_DESC}}, "required": ["target_id", "address"]}),
    ("read", "re_disassemble", _t.disassemble, "Disassemble one function to assembly in the sandbox by NAME or by hex ADDRESS (an address resolves to the function containing it) — when you need instruction-level detail the decompiler smooths over. QUERY: records an Observation; adds no graph nodes. Pass `function` or `address`. A long listing is truncated to max_chars with a marker naming both recovery paths (re-call with a bigger max_chars, or obs_get for the full body).",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "function": {"type": "string", "description": "function name (or pass `address`)"}, "address": {"type": "string", "description": "hex address (or pass `function`)"}, "max_chars": {"type": "integer", "description": _MAX_CHARS_DESC}}, "required": ["target_id"]}),
    ("read", "re_disassemble_range", _t.disassemble_range, "Disassemble a RAW ADDRESS + LENGTH byte range in the sandbox (radare2) — NO function needed, for a CFG blind spot BOTH backends miss. Reach for this when re_disassemble (by name/address, needs a defined function) and re_decompile_at (the function containing an address) both return 'not found' because no function is defined there — the only way to read the instructions when the call graph has a hole. Disassembles `length` bytes from hex `address` (default 256, clamped 1–8192), or `count` instructions if given (clamped 1–1024). QUERY: records an Observation; adds no graph nodes. A long listing is truncated to max_chars with a marker naming both recovery paths (re-call with a bigger max_chars, or obs_get for the full body).",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "address": {"type": "string", "description": "hex start address, e.g. 0x67158"}, "length": {"type": "integer", "description": "bytes to disassemble (default 256, clamped 1–8192)"}, "count": {"type": "integer", "description": "instructions to disassemble (overrides length; clamped 1–1024)"}, "max_chars": {"type": "integer", "description": _MAX_CHARS_DESC}}, "required": ["target_id", "address"]}),
    ("read", "re_reanalyze", _t.reanalyze, "Re-run a target's analysis at a HIGHER depth (busting the cached analysis) so a function or call edge the fast pass missed gets a second chance — use when re_list_functions/re_decompile_function look incomplete (missing a function you expect, or empty callees). QUERY: refreshes the inventory and records an Observation; adds no graph nodes.",
     {"type": "object", "properties": {"target_id": {"type": "string"}}, "required": ["target_id"]}),
    ("read", "re_recover_constant", _t.recover_constant, "Recover the CONSTANT/key a self-contained routine derives at runtime (a license code, an XOR key, a decoded string) by EMULATING it in Ghidra's P-Code interpreter IN THE SANDBOX — the JVM interpreter, never native execution, no network. Use when a value never appears as a literal and re_decompile_function shows only the arithmetic that computes it. ENRICH: on success tags the value onto the function node (attrs.recovered_constant) and records an emulation Observation; adds no new graph nodes. Best on a SELF-CONTAINED, parameterless routine — one taking arguments is emulated over uninitialized inputs and usually won't reach a clean ret, so it yields no recoverable value; when the recovered signature shows args it RETURNS EARLY without emulating (skipped=arg_dependent) and points you at re_solve_constraint. Gated: features.emulation (+ Ghidra headless; returns available=false when Ghidra is off).",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "function": {"type": "string", "description": "the self-contained routine to emulate"}}, "required": ["target_id", "function"]}),
    ("read", "re_imports", _t.read_imports, "The target's imported symbols, linked libraries (DT_NEEDED), and exploit-mitigation flags — a quick look at which external functions it calls, so you can spot dangerous libc imports (system/exec/strcpy/sprintf) and judge the hardening (NX/PIE/canary) at a glance. A lighter view than re_binutils_facts; reach for that when you need the full, uncapped symbol table + relocations.",
     {"type": "object", "properties": {"target_id": {"type": "string"}}, "required": ["target_id"]}),
    ("read", "re_binutils_facts", _t.binutils_facts, "Authoritative low-level ELF facts via GNU binutils (nm/objdump/readelf/strings) run in the sandbox: the symbol table, dynamic imports/exports, relocations (incl. PLT jump-slot imports), sections, ELF/program headers, and the security mitigations (NX, RELRO, PIE, stack canary, FORTIFY) — the fast first-minute facts pass, sharper than target_facts/re_imports (recon caps imports/strings). QUERY: records a binutils_facts Observation and tags is_sink on any dangerous import ALREADY in the graph + folds the mitigation flags onto the target; adds NO new graph nodes — promote what matters. Check obs_list(target_id) first to reuse a prior pass.",
     {"type": "object", "properties": {"target_id": {"type": "string"}}, "required": ["target_id"]}),
    ("read", "re_list_strings", _t.list_strings, "GREP a target's FULL string table (the real strings(1) pass over the binary, NOT a small recon sample) for a substring `pattern` — hardcoded creds, URLs, format strings (%s), command templates (.cgi), config keys (factory/aes) anywhere in the binary. Server-side filtered + PAGINATED: pass `pattern` to filter, `offset`/`limit` to page (default 200, max 1000); the result reports the total match count + the next offset to page on (no obs_get dance). With no `pattern` it lists the table page by page. QUERY: records an Observation; adds no graph nodes. Falls back to the ~40-entry recon sample (flagged in the result) ONLY when the full strings pass is unavailable — a non-ELF artifact or the sandbox image being down. For OBFUSCATED stack/decoded strings a plain pass misses (PE/x86 only), use re_floss_strings.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "pattern": {"type": "string", "description": "substring to grep the full string table for"}, "offset": {"type": "integer", "description": "page start index into the matches (default 0)"}, "limit": {"type": "integer", "description": "max strings to return (default 200, clamped 1–1000)"}}, "required": ["target_id"]}),
    ("read", "re_floss_strings", _t.floss_strings, "Recover OBFUSCATED strings a plain re_list_strings pass MISSES — STACK strings (built byte-by-byte on the stack at runtime), TIGHT strings, and DECODED strings (produced by a decode routine FLOSS lightly EMULATES in the sandbox) — via FLARE FLOSS. On firmware/malware these hidden strings (URLs, command templates, keys, format strings) are often the lead. QUERY: records a floss_strings Observation; adds NO graph nodes — PROMOTE an interesting recovered string to a string node deliberately (graph_create_node node_type=string). FLOSS is slow, so check obs_list(target_id) first to reuse a prior pass. NOTE: stack/tight/decoded recovery is x86/amd64 PE ONLY — an INHERENT vivisect/FLOSS limitation, not a bug; on an ELF/foreign-arch artifact (most firmware) it degrades to a static-strings pass (equivalent to a plain strings) with a note, so don't expect hidden-string recovery on firmware — use re_list_strings to grep the static table there. Always-on static tool (no gate — FLOSS emulates decode routines in-process and never executes the target, so it relaxes no boundary); slower than re_list_strings, hence the obs_list reuse check above.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "min_length": {"type": "integer", "description": "min string length (default 4, clamped 4–64)"}}, "required": ["target_id"]}),
    ("read", "re_yara_scan", _t.yara_scan, "Match ONE target's bytes against YARA rules (the bundled high-signal set — embedded creds, known-bad library banners, weak-crypto constants, packer signatures — plus any .yar the user dropped in the HEXGRAPH_HOME rules dir), run in the sandbox. PROMOTE: each matched rule becomes a project-level `pattern` node + a `matches_rule` edge from this target, carrying the rule's DECLARED severity/cve (the matcher never fabricates a severity or auto-mints a finding — promote a match to a finding deliberately). Records a yara_matches Observation; check obs_list(target_id, kind='yara_matches') first to reuse a prior pass. `ruleset` (a bundled ruleset id, or 'all', default 'all') is the only knob — never a yara command line. The pattern complement to the exact-hash n-day link finding_link_same_code. For the WHOLE project (every target + extracted firmware file) use re_yara_sweep. Always-on static tool (no gate — a static MATCH reads bytes and never executes, so it relaxes no boundary); drop your own .yar rules in the HEXGRAPH_HOME rules dir.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "ruleset": {"type": "string", "description": "bundled ruleset id, or 'all' (default)"}}, "required": ["target_id"]}),
    ("write", "re_yara_sweep", _t.yara_sweep, "Project-wide YARA sweep — the PATTERN n-day complement to finding_link_same_code (exact hash): match every non-archived byte target AND every extracted firmware file against the bundled high-signal rules (+ any user .yar in the HEXGRAPH_HOME rules dir), recording a yara_matches Observation per artifact and promoting matched rules to shared project-level `pattern` nodes via `matches_rule` edges (so the graph shows which targets/files a rule matched). One analyst's rule → a corpus-wide hunt. `ruleset` is a bundled ruleset id (or 'all', default). The matcher carries each rule's DECLARED severity/cve onto the pattern node but never fabricates a severity or auto-mints a finding — promote a hit to a finding deliberately. Returns a roll-up of scanned/match/promotion counts + hits. Always-on static tool (no gate — a static MATCH relaxes no boundary).",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "ruleset": {"type": "string", "description": "bundled ruleset id, or 'all' (default)"}}, "required": ["project_id"]}),
    ("run", "re_solve_reaching_input", _t.solve_reaching_input, "SOLVE for a concrete input that DRIVES execution to a sink (e.g. system/execve/strcpy) via angr SYMBOLIC EXECUTION in the dedicated angr sandbox image — the strongest STATIC claim short of a live PoC, because it produces a concrete REACHING INPUT (often raw non-ASCII bytes a guess can't hit). You REQUEST it with a sink selector — you never write an angr script; HexGraph runs the bounded, deterministic solve (DFS + wall-clock/step/state caps). PROMOTE: on success it promotes the grounded path (the sink as an is_sink node + the enclosing function + a `calls` edge) and emits a high-confidence `vulnerability` finding whose evidence.reproducer is the solved input (hex), assurance input_reachable/static; records a `solver` Observation either way. `sink_func` (the dangerous callee to reach, e.g. 'system') is the main knob; optionally `function` (the enclosing routine) and `budget`. angr is HEAVY + slow — check obs_list(target_id, kind='solver') first to reuse a prior solve. Returns cleanly unsolved when no reaching input exists within the budget (nothing fabricated). Gated: features.angr (symbolic execution; relaxes no sandbox/exec/egress boundary — it explores bytes, never runs the target — but heavy, so policy-gated like emulation).",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "sink_func": {"type": "string", "description": "the dangerous callee to reach, e.g. 'system'"}, "function": {"type": "string", "description": "optional enclosing routine"}, "budget": {"type": "string", "enum": ["quick", "default", "deep"]}}, "required": ["target_id", "sink_func"]}),
    ("run", "re_solve_constraint", _t.solve_constraint, "Recover the VALUE/input that SATISFIES a single check (the secret a strcmp compares against, the serial a license gate validates) via angr — the symbolic-execution analogue of re_recover_constant (which emulates a self-contained routine). You give a check selector; HexGraph runs the bounded solve in the angr image. ENRICH: on success annotates the function node with the recovered value (attrs.recovered_value / satisfying_input_hex) and records a `solver` Observation; adds no new graph nodes. Single-check solving ONLY — NOT whole-program exploration. `function` names the routine; optionally `check_addr` pins the pass/success block, or `sink_func` when the check gates a sink and you don't know the pass block; `budget` is quick|default|deep. Gated: features.angr (heavy, policy-gated like emulation; relaxes no boundary).",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "function": {"type": "string"}, "check_addr": {"type": "string"}, "sink_func": {"type": "string"}, "budget": {"type": "string", "enum": ["quick", "default", "deep"]}}, "required": ["target_id"]}),
    ("read", "re_xrefs", _t.xrefs, "Cross-references: which functions CALL a symbol/sink and where (omit `symbol` to map dangerous sinks, format-string sinks, AND network/socket surface bind/listen/connect/recv). Trace a sink back to its caller, or find listen/connect sites to model as socket nodes. QUERY: records an Observation and tags is_sink on any dangerous-import symbol ALREADY in the graph; adds no new graph nodes.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "symbol": {"type": "string", "description": "sink/symbol name; omit to map ALL dangerous + format + network sinks"}}, "required": ["target_id"]}),
    ("read", "re_call_graph", _t.call_graph, "The target's CALL GRAPH (who-calls-whom across the program), or — with a `function` — the neighbourhood rooted at it out to `depth` (default 2). Returns the whole-program graph, falling back to the recon-computed graph in the Observation store when the probe path comes up empty (so you see the structure without promoting functions one by one). QUERY: records a call_graph Observation that also SELF-WIRES `calls` edges among functions ALREADY in the graph (promote functions to curate the wired graph); creates no new nodes. Use to see the program's structure / a function's reachable callees without decompiling each.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "function": {"type": "string", "description": "optional root; omit for the whole-program graph"}, "depth": {"type": "integer", "description": "neighbourhood radius around `function` (default 2)"}}, "required": ["target_id"]}),
    ("read", "re_function_xrefs", _t.function_xrefs, "Both directions for ONE function: its CALLERS (who calls it) AND its CALLEES (what it calls) — walk the call graph around a function of interest (the bidirectional complement to re_xrefs, which is callers-of-a-sink only). QUERY: records an Observation; adds no graph nodes.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "function": {"type": "string"}}, "required": ["target_id", "function"]}),
    ("read", "re_data_xrefs", _t.data_xrefs, "Cross-references TO a hex ADDRESS (or a symbol/label that resolves to one) — every code/data/string reference that points at it (who reads/writes/points to this datum or string constant). Use after re_list_strings/decompile surfaces an interesting address to find who touches it. QUERY: records an Observation; adds no graph nodes.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "address": {"type": "string", "description": "hex address, or a symbol/label that resolves to one"}}, "required": ["target_id", "address"]}),
    ("read", "re_search_decompiled", _t.search_decompiled, "Search ACROSS already-decompiled function BODIES on a target for a string/identifier (a variable/constant/call/format string) — mines PRIOR decompilations in the Observation store (NO re-decompile), returns the matching functions + a snippet. Pair with re_decompile_function: decompile candidates first, then grep their bodies here. QUERY: records an Observation; adds no graph nodes. A long hit list is truncated to max_chars with a marker naming both recovery paths (re-call with a bigger max_chars, or obs_get for the full payload).",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "query": {"type": "string", "description": "substring/identifier to grep across decompiled bodies"}, "max_chars": {"type": "integer", "description": _MAX_CHARS_DESC}}, "required": ["target_id", "query"]}),

    # ---- fs: a target's unpacked filesystem -----------------------------------------
    ("read", "fs_list", _t.list_filesystem, "List a firmware target's unpacked filesystem (paths/sizes/which are ELFs or already child targets) — find config files, scripts, keys, web assets to read with fs_read_file (or promote a binary with target_promote_file). PAGINATED + filterable for big firmware (a real image unpacks to hundreds-to-thousands of files; an unfiltered dump overflows context): `path_prefix` scopes to a directory (e.g. 'usr/sbin'), `elf_only=true` lists only binaries, `offset`/`limit` page (default 200, max 2000). The result reports `total` + `next_offset` so you can page the rest. Returns {unpacked, method, files:[{rel,size,is_elf,added,revealed,child_target_id}], total, offset, next_offset, has_more}.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "path_prefix": {"type": "string", "description": "list only entries whose path starts with this (e.g. 'usr/sbin')"}, "elf_only": {"type": "boolean", "description": "list only ELF binaries (find daemons/CGIs to promote)"}, "offset": {"type": "integer", "description": "page start index into the (filtered) list (default 0)"}, "limit": {"type": "integer", "description": "max entries to return (default 200, clamped 1–2000)"}}, "required": ["target_id"]}),
    ("read", "fs_read_file", _t.read_file, "Read ONE file from a firmware target's unpacked filesystem (config/script/key/web template — NOT the raw binary; use re_decompile_function for code). Bounded 256 KiB, path-traversal safe; text as-is, binary as hex. `path` is relative to the extracted root (see fs_list).",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "path": {"type": "string", "description": "file path relative to the extracted root (see fs_list)"}}, "required": ["target_id", "path"]}),

    # ---- obs: the Observation store -------------------------------------------------
    ("read", "obs_list", _t.list_observations, "Prior deterministic analysis on a target — the OBSERVATION STORE (the substrate, NOT the curated graph): decompilations, function lists, xrefs, taint, strings, structs, each recorded once as a reusable Observation. Returns row metadata newest-first (id/tool/result_kind/summary); obs_get(id) loads the full payload from CAS. CHECK THIS BEFORE RE-RUNNING a heavy analysis — results persist here, so analyze once and reuse forever; promote only what matters into the graph.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "tool": {"type": "string", "description": "optional filter by the producing tool"}, "kind": {"type": "string", "description": "optional filter by result_kind (decompilation/xrefs/taint/…)"}, "limit": {"type": "integer"}}, "required": ["target_id"]}),
    ("read", "obs_get", _t.get_observation, "Read ONE Observation in full incl. its complete payload from CAS — reuse a prior decompilation/xref/taint result instead of paying to re-run it. Observations are the substrate (NOT graph nodes); promote the few that matter into the graph deliberately.",
     {"type": "object", "properties": {"observation_id": {"type": "string"}}, "required": ["observation_id"]}),
    ("read", "obs_search", _t.search_observations, "Search prior Observations (substring over tool/summary/result_kind) across a project or one target — find earlier analysis to reuse before re-running it.",
     {"type": "object", "properties": {"query": {"type": "string"}, "project_id": {"type": "string"}, "target_id": {"type": "string"}, "limit": {"type": "integer"}}, "required": ["query"]}),

    # ---- graph: the curated node/edge/hypothesis graph ------------------------------
    ("read", "graph_search", _t.search, "Keyword-search the CURATED graph — finding titles and promoted function/node names — to relocate something already in the graph by name. This is one of three searches, each over a different corpus: graph_search (the curated graph, here), obs_search (the raw Observation store of prior tool runs), and re_search_decompiled (the text of decompiled function bodies). Pick by what you're looking for.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "q": {"type": "string", "description": "keyword/substring to match against finding titles + node names"}}, "required": ["project_id", "q"]}),
    ("read", "graph_get_node", _t.get_node, "Read ONE node in full by id — its type, address, and every attr you set (a function's summary/params, a sink's operation/why) — to confirm a graph_create_node landed or inspect a node another agent/task added.",
     {"type": "object", "properties": {"node_id": {"type": "string"}}, "required": ["node_id"]}),
    ("read", "graph_list_nodes", _t.list_nodes, "List the curated graph's nodes (optionally filtered to one target or one node_type) with their address + attrs — survey what's already promoted before adding more, or look up a node's id to wire an edge to it.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "target_id": {"type": "string", "description": "optional: only this target's nodes"}, "node_type": {"type": "string", "enum": NODE_TYPES, "description": "optional filter by node type"}}, "required": ["project_id"]}),
    ("read", "graph_list_edges", _t.list_edges, "List the graph's edges (optionally only those touching a given node) with their type + attrs — confirm the dataflow/relationships you wired, or get an edge's id to update or delete it.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "node_id": {"type": "string", "description": "optional: only edges touching this node"}}, "required": ["project_id"]}),
    ("read", "graph_list_sockets", _t.list_sockets, "List socket endpoints (tcp/udp/unix/…) with who listens/connects on each — the firmware's network map (server↔client over shared sockets).",
     {"type": "object", "properties": {"project_id": {"type": "string"}}, "required": ["project_id"]}),
    ("read", "graph_list_hypotheses", _t.list_hypotheses, "The project's hypothesis WORKLIST — a row per hypothesis with its statement, evidence status (open/supported/refuted/contested + pinned verdicts), work_state (investigating/parked/done), pinned_to_graph flag, and support/refute counts. Filter by `work_state` and/or evidence `status`. Your 'what am I working on / chasing' orient before recording a new hypothesis or resuming a session; pair with graph_create_hypothesis (add) and graph_close_hypothesis (check off).",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "work_state": {"type": "string", "enum": HYPOTHESIS_WORK_STATES, "description": "optional filter: investigating/parked/done"}, "status": {"type": "string", "enum": HYPOTHESIS_STATUSES, "description": "optional filter by evidence verdict"}}, "required": ["project_id"]}),
    ("read", "graph_stats", _t.graph_stats, "Per-type node/edge TALLIES for the project's live graph (nodes_by_type, edges_by_type, totals + target/finding counts) — get before/after counts to see what a task or your curation added, WITHOUT graph_list_nodes (which truncates at 500 and can't count a large graph). Archived targets/nodes excluded.",
     {"type": "object", "properties": {"project_id": {"type": "string"}}, "required": ["project_id"]}),
    ("write", "graph_create_node", _t.create_node, "PROMOTE: deliberately add a curated result to the graph as a node. The graph is a curated result set, so add only nodes that carry your reasoning, not the binary's whole structure. ALWAYS pass target_id for target-bound types (else it's an orphan); it auto-links to its target and pulls any waiting always-welcome facts (prototype/address) from prior Observations. Populate `attrs` with the type's recommended fields from meta_get_schemas.node_attribute_schemas (function->summary+params, input->source, sink->operation+why). A dangerous call (system/strcpy) is a symbol/function node with is_sink=true — NOT a separate `sink` node. Pass `address` for code nodes.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "node_type": {"type": "string", "enum": NODE_TYPES, "description": "the curated entity's type"}, "name": {"type": "string"}, "target_id": {"type": "string", "description": "REQUIRED for target-bound types, else the node is an orphan"}, "address": {"type": "string", "description": "hex address for code nodes"}, "attrs": {"type": "object", "description": "type-specific attributes (see meta_get_schemas.node_attribute_schemas)"}}, "required": ["project_id", "node_type", "name"]}),
    ("write", "graph_create_edge", _t.create_edge, "Connect two graph entities (target|node|finding|task) with a typed, attributed edge. The required `type` param (NOT `edge_type`) names the relationship — one of the EdgeType vocabulary that meta_get_schemas lists under `edge_types`. `attrs` carries edge-type facts (see meta_get_schemas: e.g. calls→call_sites/arg_constraints, listens_on→address). merge=True accumulates list attrs. A hypothesis is a 'node'; or use graph_link_evidence to attach a finding to one.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "src_kind": {"type": "string", "enum": ["target", "node", "finding", "task"], "description": "source endpoint kind"}, "src_id": {"type": "string"}, "dst_kind": {"type": "string", "enum": ["target", "node", "finding", "task"], "description": "destination endpoint kind"}, "dst_id": {"type": "string"}, "type": {"type": "string", "enum": EDGE_TYPES, "description": "REQUIRED — the edge relationship type, an EdgeType value (the vocab meta_get_schemas reports as `edge_types`). Pass it as `type`, not `edge_type`."}, "attrs": {"type": "object", "description": "edge-type attributes (see meta_get_schemas.edge_attribute_schemas)"}, "merge": {"type": "boolean", "description": "accumulate list attrs instead of replacing"}}, "required": ["project_id", "src_kind", "src_id", "dst_kind", "dst_id", "type"]}),
    ("write", "graph_update_edge", _t.update_edge, "Add/update attributes on an EXISTING edge by id (merge=True accumulates list attrs like call_sites; merge=False replaces). See meta_get_schemas for per-type attributes.",
     {"type": "object", "properties": {"edge_id": {"type": "string"}, "attrs": {"type": "object"}, "merge": {"type": "boolean"}}, "required": ["edge_id", "attrs"]}),
    ("write", "graph_set_node_attr", _t.set_node_attr, "Set ONE attribute on an existing node by id (e.g. is_sink=true, or attrs.entry=true to mark a reachability source) WITHOUT re-sending the whole node via graph_create_node. Sets just `key`; the node's other attrs are untouched. Returns the updated node.",
     {"type": "object", "properties": {"node_id": {"type": "string"}, "key": {"type": "string", "description": "the attribute name (e.g. is_sink, entry)"}, "value": {"description": "the attribute value (any JSON type — bool/string/number/list/object)"}}, "required": ["node_id", "key", "value"]}),
    ("write", "graph_create_socket", _t.create_socket, "Create/reuse a SOCKET graph NODE (a network/IPC endpoint shared across binaries — NOT a live target; for a fuzzable live service use target_register_service). Give port or name. A server listens_on it, a client connects_to it — both resolve to one node.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "kind": {"type": "string", "enum": SOCKET_KIND_VALUES, "description": "socket kind"}, "port": {"type": ["integer", "string"], "description": "port (give port or name)"}, "name": {"type": "string", "description": "named endpoint (e.g. a unix socket path)"}, "bind_addr": {"type": "string"}, "attrs": {"type": "object"}}, "required": ["project_id"]}),
    ("write", "graph_create_hypothesis", _t.create_hypothesis, "Record a research hypothesis (a falsifiable open QUESTION you're chasing — NOT a settled fact, which is a node/edge/finding) anchored to a target; it lands on your live worklist as work_state='investigating' and stays OFF the canvas unless pinned. Confirm/refute it by attaching findings with graph_link_evidence, then graph_close_hypothesis when you've settled it. See graph_list_hypotheses for the worklist.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "statement": {"type": "string"}, "rationale": {"type": "string"}, "target_id": {"type": "string"}}, "required": ["project_id", "statement"]}),
    ("write", "graph_link_evidence", _t.link_evidence, "Attach a finding to a hypothesis as supporting/refuting evidence (recomputes the hypothesis status). This is how you confirm a hypothesis.",
     {"type": "object", "properties": {"hypothesis_id": {"type": "string"}, "finding_id": {"type": "string"}, "relation": {"type": "string", "enum": EVIDENCE_RELATIONS, "description": "does the finding support or refute the hypothesis"}}, "required": ["hypothesis_id", "finding_id", "relation"]}),
    ("write", "graph_set_hypothesis_status", _t.set_hypothesis_status, "Update a hypothesis along EITHER axis (pass at least one): `status` pins the evidence verdict (when you're not driving it through graph_link_evidence); `work_state` moves the orthogonal worklist axis (investigating | parked | done). Pass `rationale` to record why.",
     {"type": "object", "properties": {"hypothesis_id": {"type": "string"}, "status": {"type": "string", "enum": HYPOTHESIS_STATUSES, "description": "the evidence verdict"}, "work_state": {"type": "string", "enum": HYPOTHESIS_WORK_STATES, "description": "the worklist axis (investigating/parked/done) — orthogonal to status"}, "rationale": {"type": "string"}}, "required": ["hypothesis_id"]}),
    ("write", "graph_close_hypothesis", _t.close_hypothesis, "CHECK OFF a hypothesis: set work_state='done' and optionally record the evidence `verdict` (confirmed | rejected | supported | refuted | …) for how it resolved — a proven question closes confirmed/supported, a ruled-out one refuted/rejected (a documented dead end). Use when you've settled a hypothesis either way; park (graph_set_hypothesis_status work_state='parked') one you've only set aside.",
     {"type": "object", "properties": {"hypothesis_id": {"type": "string"}, "verdict": {"type": "string", "enum": HYPOTHESIS_STATUSES, "description": "optional evidence verdict explaining how it closed"}, "rationale": {"type": "string"}}, "required": ["hypothesis_id"]}),
    ("write", "graph_annotate", _t.annotate, "Attach a note/tag/rename/type_decl to a graph entity (agent PROPOSAL, pending analyst approval). A confirmed `rename` round-trips into the persistent Ghidra project and re-decompiles, so the new name sticks for every future decompile. For parameters/explanations on a function, prefer graph_create_node attrs.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "node_kind": {"type": "string", "enum": ANNOTATION_NODE_KINDS, "description": "the kind of entity being annotated"}, "node_id": {"type": "string"}, "kind": {"type": "string", "enum": ANNOTATION_KINDS, "description": "annotation kind"}, "value": {"type": "string", "description": "the note text / tag / new name / type decl"}}, "required": ["project_id", "node_kind", "node_id", "kind", "value"]}),
    ("write", "graph_merge_duplicates", _t.merge_duplicates, "Fold duplicate nodes/binaries into one canonical node (e.g. the decompiler's `sym.foo` and a hand-added `foo`, or the same binary ingested twice), moving ALL their edges/findings/annotations onto the keeper — nothing is lost. Runs automatically after LLM tasks; call it on demand after you've bulk-added nodes, to de-dup the graph.",
     {"type": "object", "properties": {"project_id": {"type": "string"}}, "required": ["project_id"]}),
    ("write", "graph_archive_node", _t.archive_node, "Soft-remove a node from the graph (REVERSIBLE): hides the node and the edges touching it. Re-adding the same node (graph_create_node/a task) or graph_restore_node brings it and its edges back — nothing is deleted.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "node_id": {"type": "string"}}, "required": ["project_id", "node_id"]}),
    ("write", "graph_restore_node", _t.restore_node, "Un-archive a previously soft-removed node; its hidden edges reappear.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "node_id": {"type": "string"}}, "required": ["project_id", "node_id"]}),
    ("write", "graph_delete_edge", _t.delete_edge, "Permanently delete ONE edge by id (hard delete — recreate with graph_create_edge to restore). To remove a node's edges reversibly, graph_archive_node instead.",
     {"type": "object", "properties": {"edge_id": {"type": "string"}}, "required": ["edge_id"]}),

    # ---- journal: the freeform research notebook (interpreted narrative) -------------
    ("write", "journal_add", _t.add_journal_entry, "Add an entry to the freeform research JOURNAL — the INTERPRETED-NARRATIVE notebook shared with the human (the idea you had, what you TRIED, what worked/didn't, what you LEARNED), NOT the Observation store (raw tool output — recorded automatically) or findings (substantiated results, finding_record). Always posts as the AGENT (you can't author as the human). Write a short line at each meaningful pivot or dead end and at task close, not one dump at the end. @[label](kind:id) mentions (kind = node|finding|target|hypothesis) become clickable links — mention objects instead of re-describing them. Keep it skimmable.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "body": {"type": "string", "description": "markdown body; @[label](kind:id) to mention a graph object"}, "origin_task_id": {"type": "string", "description": "optional: the task/session this entry came from"}}, "required": ["project_id", "body"]}),
    ("read", "journal_list", _t.list_journal_entries, "List a project's JOURNAL entries (interpreted narrative notes) newest-first, optionally filtered by author — your running log of what you tried and learned, distinct from obs_list (raw tool output) and finding_list (substantiated results). Use to re-orient at the start of a session.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "author": {"type": "string", "enum": JOURNAL_AUTHORS, "description": "optional filter: human | agent"}, "limit": {"type": "integer"}}, "required": ["project_id"]}),
    ("read", "journal_get", _t.get_journal_entry, "Read ONE journal entry in full, with its @-mentions resolved (a merged/archived target is flagged dangling) — the journal analog of finding_get / graph_get_node.",
     {"type": "object", "properties": {"entry_id": {"type": "string"}}, "required": ["entry_id"]}),
    ("read", "journal_search", _t.search_journal, "Search the freeform research JOURNAL (interpreted narrative notes) — NOT Observations (raw tool output, obs_search) or findings (finding_list). Substring over entry bodies, newest first. Your highest-value cross-session memory: journal_search('what did I try on the CGI handler') re-orients a fresh session in one call.",
     {"type": "object", "properties": {"query": {"type": "string"}, "project_id": {"type": "string"}, "limit": {"type": "integer"}}, "required": ["query", "project_id"]}),
    ("write", "journal_update", _t.update_journal_entry, "Edit one of YOUR OWN journal entries by id (refuses a HUMAN-authored entry — the journal is a trust artifact, the human's words stay theirs). Marks the entry edited and re-parses its @-mentions.",
     {"type": "object", "properties": {"entry_id": {"type": "string"}, "body": {"type": "string", "description": "the new markdown body"}}, "required": ["entry_id", "body"]}),
    ("write", "journal_delete", _t.delete_journal_entry, "Delete one of YOUR OWN journal entries by id (refuses a HUMAN-authored entry). Hard delete — re-add with journal_add if needed.",
     {"type": "object", "properties": {"entry_id": {"type": "string"}}, "required": ["entry_id"]}),

    # ---- finding: findings, n-day, proving ------------------------------------------
    ("read", "finding_list", _t.list_findings, "Existing findings in a project, NEWEST-FIRST (each row carries finding_type + verified flag + the compact assurance triple). Paginated and filterable. BY DEFAULT excludes the high-volume `recon` findings (ingest mints one per child target — easily hundreds); pass include_recon=true (or finding_type='recon') to include them.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "limit": {"type": "integer", "description": "max rows (default 100; 0 = no limit)"}, "offset": {"type": "integer", "description": "skip this many (for paging, default 0)"}, "finding_type": {"type": "string", "enum": FINDING_TYPE_VALUES, "description": "filter by producing-task class (e.g. vulnerability/fuzz_crash/poc); set 'recon' to see the per-child recon rows"}, "status": {"type": "string", "enum": FINDING_STATUSES, "description": "filter by triage status"}, "severity": {"type": "string", "enum": SEVERITIES, "description": "filter by severity"}, "target_id": {"type": "string", "description": "only findings on this target"}, "verified": {"type": "boolean", "description": "only PoC-verified (true) or only unverified (false) findings; pagination is over the verified-filtered set"}, "include_recon": {"type": "boolean", "description": "include the high-volume recon findings (default false)"}}, "required": ["project_id"]}),
    ("read", "finding_get", _t.get_finding, "Read ONE finding in full incl. complete evidence (evidence.extra holds the finding_verify_poc result) — confirm a write landed (finding analog of graph_get_node).",
     {"type": "object", "properties": {"finding_id": {"type": "string"}}, "required": ["finding_id"]}),
    ("write", "finding_record", _t.record_finding, "Record a new finding (the `finding` dict must match the Finding schema — call meta_get_schemas). `finding_type` is a SEPARATE arg, not a finding field. A `cwe` in evidence.extra (e.g. \"CWE-787\") is lifted to a first-class, filterable triage field. Pass task_id in delegate mode.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "target_id": {"type": "string"}, "finding": {"type": "object", "description": "the Finding-schema dict (call meta_get_schemas['finding'] for the full shape)", "properties": {
        "title": {"type": "string", "description": "one-line headline naming the flaw + where"},
        "severity": {"type": "string", "enum": SEVERITIES},
        "confidence": {"type": "string", "enum": CONFIDENCES},
        "category": {"type": "string", "enum": CATEGORIES, "description": "the flaw class (NOT the finding_type arg)"},
        "summary": {"type": "string", "description": "what the flaw is, in a sentence or two"},
        "reasoning": {"type": "string", "description": "why it's a flaw — the analysis, citing the evidence"},
        "evidence": {"type": "object", "description": "function/sink/address/reproducer + extra (assurance, cwe, …); see meta_get_schemas['finding']"},
     }, "required": ["title", "severity", "confidence", "category", "summary", "reasoning", "evidence"]}, "finding_type": {"type": "string", "enum": FINDING_TYPE_VALUES, "description": "the producing-task class (a DB envelope field, not part of the frozen Finding schema)"}, "task_id": {"type": "string", "description": "delegate mode only"}}, "required": ["project_id", "target_id", "finding"]}),
    ("write", "finding_update", _t.update_finding, "Update an EXISTING finding in place (status/severity/confidence/human_notes/cwe) — e.g. confirm it after a PoC verifies, or set/correct the triage CWE. Don't create a duplicate.",
     {"type": "object", "properties": {"finding_id": {"type": "string"}, "status": {"type": "string", "enum": FINDING_STATUSES, "description": "triage status"}, "severity": {"type": "string", "enum": SEVERITIES}, "confidence": {"type": "string", "enum": CONFIDENCES}, "human_notes": {"type": "string"}, "cwe": {"type": "string", "description": "CWE id (e.g. CWE-787 or 787) — normalized to CWE-<n>"}}, "required": ["finding_id"]}),
    ("write", "finding_delete", _t.delete_finding, "Permanently DELETE a junk finding by id (hard delete — IRREVERSIBLE; also removes every edge/annotation touching it). Use only for pure noise. To set a finding aside reversibly instead (keep the row, greyed, restorable), call finding_update(status='dismissed').",
     {"type": "object", "properties": {"finding_id": {"type": "string"}}, "required": ["finding_id"]}),
    ("write", "finding_link_to_source", _t.link_finding_to_source, "Link a finding to its location in a managed source file (a `located_in` edge + evidence.extra.source_ref) — the jump-from-finding-to-source link. tree_id/rel from src_list_trees/src_read_file; pass `line` to scroll there. Use when a vuln/harness corresponds to known source.",
     {"type": "object", "properties": {"finding_id": {"type": "string"}, "tree_id": {"type": "string"}, "rel": {"type": "string", "description": "file path within the source tree"}, "line": {"type": "integer"}, "col": {"type": "integer"}}, "required": ["finding_id", "tree_id", "rel"]}),
    ("write", "finding_link_same_code", _t.link_same_code, "Cross-target n-day primitive (bindiff/similarity): link functions with identical code (same content_hash) across DIFFERENT binaries via similar_to edges, and return the matches (each side flags has_findings). Run after confirming a bug to find the same routine reused elsewhere, then finding_propagate.",
     {"type": "object", "properties": {"project_id": {"type": "string"}}, "required": ["project_id"]}),
    ("write", "finding_propagate", _t.propagate_finding, "N-day: clone an existing finding onto another binary that shares the same code (per finding_link_same_code) as a fresh finding to triage, wired derived_from→ the source. Avoids re-typing the whole finding for 'same bug, other binary'.",
     {"type": "object", "properties": {"finding_id": {"type": "string"}, "target_id": {"type": "string"}, "function": {"type": "string"}, "notes": {"type": "string"}}, "required": ["finding_id", "target_id"]}),
    ("run", "finding_reachability", _t.reachability, "Argue STATIC input-reachability (Standard B, static): search the typed graph for a directed source→sink path so a finding can claim input_reachable/static even when you CAN'T trigger it live (a real sink, but the service won't boot — the DIR-823G case). Pass finding_id (resolves the sink it cites, RECORDS the path + upgraded assurance on the finding) and/or sink_node_id (reports a path to that sink). Sources = input/param/endpoint/socket nodes (or a function/symbol you marked attrs.entry); follows taints/calls/routes_to/reads/writes/references FORWARD (taints is the strongest signal), depth-bounded + cycle-safe. Precondition is derived from the path (crosses an auth boundary / a `bypasses` edge => requires_credentials; starts at an unauth boundary => unauthenticated; else unspecified) — OR pass `precondition` to ASSERT it yourself (e.g. `unauthenticated` when the route is pre-auth but the graph lacks the auth markers, so the inferred default would under-state it); a caller-asserted precondition is recorded as NOT inferred. An ARGUMENT, not a trigger — it only UPGRADES a code_present/static floor and NEVER downgrades a dynamic claim. Build the input/sink nodes + taints/calls edges first.",
     {"type": "object", "properties": {"finding_id": {"type": "string"}, "sink_node_id": {"type": "string"}, "max_depth": {"type": "integer"}, "precondition": {"type": "string", "enum": REACHABILITY_PRECONDITIONS, "description": "OVERRIDE the path-derived precondition (assert the principal the claim requires)"}}, "required": []}),
    ("run", "finding_verify_poc", _t.verify_poc, "Prove an exploit and report verified true/false (the gold bar). Binary target -> runs it in the sandbox (spec {argv?,argv_b64?,env?,stdin?,stdin_b64?,oracle:{output_contains|exit_code|crash}}, needs features.poc). For RAW-BYTE input (a non-printable argv serial like 0x3b25065c4b20040f, or binary stdin) use argv_b64 (list of base64'd elements, exec'd as raw bytes) / stdin_b64 instead of argv/stdin, which str()-mangle non-printable bytes. SOLVER HANDOFF: to verify an angr-solver finding's reproducer byte-faithfully, pass finding_id=<that finding> with poc={oracle:{…}} and NO argv/stdin — HexGraph fills argv_b64/stdin_b64 from evidence.extra.solver. Web surface -> sends HTTP steps (spec {steps:[{method,path,body?,...}],oracle:{body_contains|status_is|status_differs}}, cookies carry across steps for auth flows, needs features.network). Raw TCP service -> spec {transport:'tcp', port, payload, oracle:{response_contains}} (needs features.network); use for a rehosted/remote device's non-HTTP daemon. Raw UDP service -> spec {transport:'udp', port, payload, oracle:{response_contains}} (needs features.network); the datagram analogue, for a UDP daemon (infosvr/SSDP/mDNS/DNS/DHCP). Put {{NONCE}} in BOTH the payload and the oracle value for an unforgeable check. Extra oracles prove vuln classes BEYOND reflected cmdi by observing an INDEPENDENT channel (call meta_get_schemas['verify_poc_oracles'] for the spec): blind cmdi/SSRF/blind RCE -> oracle {type:'callback'} + a {{CALLBACK}} token (the target dials a bounded local listener); arbitrary READ (traversal/disclosure) -> {plant:{channel:'rootfs',path}|{known_value}} + oracle {type:'canary_read'}; arbitrary WRITE (file/config/NVRAM) -> write {{NONCE}} then oracle {type:'oob_write', channel:'rootfs'|'remote'|'http', path?|request?}; DENIAL OF SERVICE of a live web/TCP service -> oracle {type:'liveness', reprobes?, port?}. Pass finding_id to attach the result (always do this for a confirmed vuln). Gated: features.poc (binary) / features.network (web/tcp).",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "poc": {"type": "object", "description": "the self-contained PoC spec (argv/argv_b64/steps/payload + oracle; use {{NONCE}}/{{CALLBACK}}/{{CANARY}}; argv_b64/stdin_b64 carry RAW BYTES base64'd for non-printable input)"}, "finding_id": {"type": "string", "description": "attach the verification result to this finding (always do this for a confirmed vuln); for an angr-solver finding, the recovered argv/stdin is filled in byte-faithfully when the spec omits its own input"}}, "required": ["target_id", "poc"]}),

    # ---- src: source trees + builds -------------------------------------------------
    ("read", "src_list_trees", _t.list_source_trees, "List the project's managed SOURCE trees (trusted source we possess/build — NOT the hostile target). Harnesses, PoCs, and build/run scripts live here as role-tagged source_files. Returns id/name/origin/file_count + which targets are built_from each. Use src_read_file to view a tree's files.",
     {"type": "object", "properties": {"project_id": {"type": "string"}}, "required": ["project_id"]}),
    ("read", "src_read_file", _t.read_source_file, "Browse/read a managed SOURCE tree (tree_id from src_list_trees). Omit `rel` to LIST files (rel/size/role); pass `rel` to READ one file's text (bounded, traversal-safe; binary as hex). Trusted source text (a harness/PoC/build recipe / imported library source) — distinct from fs_read_file, which reads a firmware's hostile unpacked bytes.",
     {"type": "object", "properties": {"tree_id": {"type": "string"}, "rel": {"type": "string", "description": "file path within the tree; omit to LIST files"}}, "required": ["tree_id"]}),
    ("read", "src_list_builds", _t.list_builds, "List builds in a project — the build ledger. Each carries status, the reproducibility triple (recipe_sha/source_content_hash/toolchain_digest), artifacts as CAS shas, and the instrumented derived_target_id it registered. Optionally filter by source_tree_id. Returns {build_specs, builds}.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "source_tree_id": {"type": "string"}}, "required": ["project_id"]}),
    ("read", "src_build_log", _t.build_log, "The full build log (stdout+stderr of every phase, from CAS) for a build — the recipe-iteration signal on a FAILED build. Read it to see WHY a compile/instrumentation step failed (missing header, a flag the sanitizer rejected, a cross-compile sysroot miss), fix phases/env/arch, and rebuild. build_id from src_list_builds. Returns {build_id, status, returncode, error, log}.",
     {"type": "object", "properties": {"build_id": {"type": "string"}}, "required": ["build_id"]}),
    ("write", "src_import_tree", _t.import_source_tree, "Create a managed SOURCE tree and optionally populate it. `files` = [{rel,content,role?}]. Use to bring in a harness/PoC you authored or a small library's source. Trusted text only — NOT target bytes (those are target_ingest'd as targets). Returns {id,name,written}.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "name": {"type": "string"}, "files": {"type": "array", "description": "[{rel, content, role?}] — role one of " + "/".join(SOURCE_ROLES)}, "origin": {"type": "string"}}, "required": ["project_id", "name"]}),
    ("write", "src_save_revision", _t.save_source_revision, "Edit a HexGraph-AUTHORED source file (a harness/PoC/script you wrote) and save it as a NEW REVISION — never an in-place mutation, so the edit is durable + reversible and you can rebuild-from-revision (pass the returned revision id as src_build's source_revision_id). Scratch/HexGraph-authored trees are editable by default; editing OTHER authored trees needs features.source.edit. ALWAYS REFUSES an imported/extracted/vendor (read-only) tree — editing those would break the build content_hash contract. Returns {id, seq, rel, role}. Use to iterate on a harness/PoC in place rather than re-importing.",
     {"type": "object", "properties": {"tree_id": {"type": "string"}, "rel": {"type": "string"}, "content": {"type": "string"}, "role": {"type": "string", "enum": SOURCE_ROLES}, "note": {"type": "string"}}, "required": ["tree_id", "rel", "content"]}),
    ("write", "src_import_oss_fuzz", _t.import_oss_fuzz, "Import an OSS-Fuzz-style `build.sh` into a recorded build_spec so an existing OSS-Fuzz target builds in HexGraph with minimal hand-authoring. The script is stored in the (EDITABLE) tree as role=script; HexGraph maps the OSS-Fuzz env contract ($CC/$CXX/$CFLAGS/$LIB_FUZZING_ENGINE/$SRC/$OUT) to ours, so the script runs essentially unchanged, and auto-detects the $OUT/<name> fuzz targets to capture. Returns the build_spec; then src_build runs it. Bring in the source tree first (src_import_tree).",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "source_tree_id": {"type": "string"}, "build_sh": {"type": "string"}, "instrumentation": {"type": "object"}, "artifacts": {"type": "array"}}, "required": ["project_id", "source_tree_id", "build_sh"]}),
    ("run", "src_build", _t.build_target, "Build a managed SOURCE tree into an INSTRUMENTED artifact in the sandbox via a RECORDED, REPRODUCIBLE recipe (build-as-API): you author/approve a BuildSpec and REQUEST the build — you never run a compiler, HexGraph runs the recipe. `system` (auto-detected if omitted), `phases` (recorded verbatim), `instrumentation` ({sanitizers, coverage:[sancov|afl_pcguard], engine:libfuzzer|afl}), `artifacts` (rel paths to capture), `env` (NON-secret — secrets rejected). Instrumentation is INJECTED as CC/CXX/CFLAGS (base-image contract), so the SAME phases yield ASan/SanCov/AFL++ by swapping the profile. CROSS-COMPILE: pass `arch` to cross-build for a firmware's arch — HexGraph injects clang --target + the parent firmware's extracted rootfs as --sysroot (a cross-build failure degrades to qemu-mode binary-only fuzzing). DEPENDENCIES: `network` defaults 'none' (vendored/offline, fully reproducible); 'fetch' (requires features.build_fetch) runs a SEPARATE, audited, ALLOWLISTED fetch phase (`fetch_phases`) that hash-pins deps into a LOCKFILE, then DROPS NETWORK and compiles --network none; the build records a lockfile + SBOM-lite + a reproducibility BADGE, and a cache HIT REUSES the prior artifact. `source_revision_id` builds from a specific editable-IDE revision. If the tree is built_from a target, the rebuild registers a DERIVED target wired instrumented_build_of→ the original. Gated: features.build.",
     {"type": "object", "properties": {"project_id": {"type": "string"}, "source_tree_id": {"type": "string"}, "system": {"type": "string", "enum": BUILD_SYSTEMS, "description": "build system (auto-detected if omitted)"}, "phases": {"type": "array", "description": "shell phases, recorded verbatim"}, "instrumentation": {"type": "object", "description": "{sanitizers, coverage, engine} — injected via CC/CXX/CFLAGS"}, "artifacts": {"type": "array", "description": "rel paths of build outputs to capture"}, "env": {"type": "object", "description": "NON-secret build env (secrets rejected)"}, "arch": {"type": "string", "enum": ["mips", "mipsel", "arm", "armhf", "aarch64"], "description": "cross-compile target arch (matches the firmware userland)"}, "network": {"type": "string", "enum": ["none", "fetch"], "description": "dep policy (default none; fetch needs features.build_fetch)"}, "fetch_phases": {"type": "array"}, "source_revision_id": {"type": "string", "description": "build from a specific src_save_revision revision"}}, "required": ["project_id", "source_tree_id"]}),

    # ---- fuzz: campaigns, artifacts, environments, coverage -------------------------
    ("read", "fuzz_status", _t.fuzz_status, "Live status + stats of a fuzz CAMPAIGN (status, execs, edges_covered, crash_count, coverage). Reaps on read so figures are fresh. Poll this while a campaign runs — crashes stream to fuzz_crash findings as they happen, so an early crash in a long campaign surfaces within minutes.",
     {"type": "object", "properties": {"campaign_id": {"type": "string"}}, "required": ["campaign_id"]}),
    ("read", "fuzz_list_artifacts", _t.list_fuzz_artifacts, "List a campaign's DEDUPLICATED artifacts (crash/hang/leak/oom/corpus) — each with the normalized dedup_key (one representative per stack-hash bucket + dupe_count), the sanitizer crash kind, the faulting function, the deterministic exploitability rating, the CAS reproducer sha (re-runnable via finding_verify_poc / fuzz_minimize_artifact), and the fuzz_crash finding it produced.",
     {"type": "object", "properties": {"campaign_id": {"type": "string"}}, "required": ["campaign_id"]}),
    ("read", "fuzz_list_environments", _t.list_fuzz_environments, "List registered fuzz ENVIRONMENTS — where a campaign's container can run: `local` (the host Docker daemon) + N user-owned remote Docker hosts (beefier/unconstrained compute). Each carries the non-secret label/descriptor, the ResourceSpec ceiling, presence-only `connection_present` (the secret DOCKER_HOST/creds live in env/config.toml, never stored/returned), and the cached health-check. Pass an environment id to fuzz_start's `environment` arg to run a campaign there — building + fuzzing run on the remote with NO analysis change, the SAME sandbox boundary. Gated: features.fuzz_remote.",
     {"type": "object", "properties": {"project_id": {"type": "string"}}}),
    ("read", "fuzz_environment_health", _t.fuzz_environment_health, "Health-check a remote fuzz environment: is it reachable + authorized + does it have the fuzz image present (the one-time remote build/pull)? Returns a NON-SECRET {ok, reachable, authorized, image_present, docker_version, detail} — the connection string is never echoed. Gated: features.fuzz_remote.",
     {"type": "object", "properties": {"environment_id": {"type": "string"}}, "required": ["environment_id"]}),
    ("read", "fuzz_coverage_diff", _t.coverage_diff, "Run-to-run COVERAGE DIFF between two fuzz campaigns: what NEW source lines did `other_campaign_id` reach that `campaign_id` (the base) did not (and which did it lose)? The 'did this run reach new edges?' answer — use to judge whether a harness/corpus/engine change actually improved reach. Returns per-file {gained, lost} + project totals; available=False when either campaign exposed no per-line coverage map.",
     {"type": "object", "properties": {"campaign_id": {"type": "string"}, "other_campaign_id": {"type": "string"}}, "required": ["campaign_id", "other_campaign_id"]}),
    ("run", "fuzz_start", _t.start_fuzz_campaign, "Start a multi-surface fuzz CAMPAIGN on a target; returns immediately with {id, status:'running'}. You REQUEST it — you NEVER run a fuzzer; HexGraph spawns a DETACHED, hardened sandbox container and a reaper streams each unique crash → a fuzz_crash finding with a one-click-re-verifiable reproducer (via fuzz_verify_artifact). `surface` auto-infers from the target (override surface/engine, validated fail-closed): source_lib (an INSTRUMENTED derived target, with source) → AFL++ coverage-guided; binary_only (a stripped firmware ELF, NO source) → AFL++ qemu-mode (engine='qemu' default; engine='frida' alt; foreign-arch MIPS/ARM runs under qemu-user + the parent firmware rootfs as sysroot); network (a LIVE service) → boofuzz (engine='boofuzz' default — pass host/port/proto_spec if not on the target; a crash = service death = input_reachable/dynamic, the strongest assurance) or engine='desock' (coverage-fuzz a LOCAL server binary with --network none). file_format → AFL++ + auto-dictionary. `instances` = AFL++ master + N-1 secondaries. `resources` = a ResourceSpec override; `unconstrained` lifts mem/cpu/pids ONLY (the sandbox security flags always hold). `environment` selects WHERE the container runs (fuzz_list_environments): omit/'local' for the host daemon, or a registered remote Docker host. Optional `seeds`/`dictionary` shape the search; `max_len` caps input size. Source-fuzz instrumentation knobs (each defaults to its features.fuzzing.* setting): `bug_oracles` (AFL++ 5.x SCALAR/BUDGET/SIZEFILL/ALLOCSIZE/SLACK detectors), `path_coverage` 0-3 (Ball-Larus path sensitivity), `cmplog` (magic-byte/memcmp gating). Then poll fuzz_status + read fuzz_list_artifacts. Gated by surface: source/binary-only/desock need features.fuzzing (or features.poc); a LIVE-socket boofuzz campaign needs features.network; a remote environment needs features.fuzz_remote.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "surface": {"type": "string", "enum": FUZZ_SURFACES, "description": "attack surface (auto-inferred from the target if omitted)"}, "engine": {"type": "string", "enum": FUZZ_ENGINES, "description": "fuzz engine (surface-defaulted if omitted)"}, "function": {"type": "string"}, "max_total_time": {"type": "integer", "description": "campaign budget seconds"}, "max_len": {"type": "integer", "description": "max input length (coverage-guided)"}, "max_crashes": {"type": "integer"}, "instances": {"type": "integer", "description": "AFL++ master + N-1 secondaries"}, "seeds": {"type": "array", "items": {"type": "string"}, "description": "host seed-corpus file paths (optional)"}, "dictionary": {"type": "array", "items": {"type": "string"}, "description": "fuzzing dictionary tokens (optional; auto-derived from the target's strings when omitted)"}, "host": {"type": "string", "description": "network surface: the live service host (loopback/private only); inferred from a rehosted/web target when omitted"}, "port": {"type": "integer", "description": "network surface: the service port; inferred from the target when omitted"}, "protocol": {"type": "string", "enum": ["tcp", "udp"], "description": "network surface: transport for boofuzz (default tcp)"}, "proto_spec": {"type": "object", "description": "network surface: the boofuzz generational request/state spec for a binary protocol"}, "launch": {"type": "boolean", "description": "network surface (launch-and-join): force HexGraph to START the service itself and join the fuzzer to its netns"}, "launch_binary": {"type": "string", "description": "network surface (launch-and-join): the server ELF path to launch"}, "launch_command": {"type": "array", "items": {"type": "string"}, "description": "network surface (launch-and-join): the FULL argv the launched server needs to stay foreground and bind its port, e.g. [\"-f\", \"-p\", \"9999\"] (each element ONE argv token — not a space-joined string)"}, "bug_oracles": {"type": "boolean", "description": "source-fuzz: enable AFL++ 5.x bug-detection oracles (SCALAR/BUDGET/SIZEFILL/ALLOCSIZE/SLACK — catches arithmetic/OOB bugs ASan misses); defaults to features.fuzzing.bug_oracles"}, "path_coverage": {"type": "integer", "enum": [0, 1, 2, 3], "description": "source-fuzz: Ball-Larus per-function path coverage — 0=off, 1=relaxed, 2=restricted, 3=strict (more signal, more overhead); defaults to features.fuzzing.path_coverage"}, "cmplog": {"type": "boolean", "description": "source-fuzz: build the CmpLog -c binary to defeat magic-byte/memcmp gates; defaults to features.fuzzing.cmplog"}, "resources": {"type": "object", "description": "ResourceSpec override {mem,cpus,pids,tmpfs,timeout,unconstrained}"}, "environment": {"type": "string", "description": "fuzz environment id (fuzz_list_environments); omit for local"}}, "required": ["target_id"]}),
    ("run", "fuzz_stop", _t.stop_fuzz_campaign, "Stop a running fuzz campaign — kills the detached container PRESERVING the corpus in CAS (resumable via fuzz_resume), after reaping any final crashes so nothing is lost.",
     {"type": "object", "properties": {"campaign_id": {"type": "string"}}, "required": ["campaign_id"]}),
    ("run", "fuzz_resume", _t.resume_fuzz_campaign, "Resume a FINISHED fuzz campaign (stopped/completed/failed/degraded), re-seeded from its preserved CAS corpus so it continues accumulating coverage + crashes instead of starting cold — the other half of fuzz_stop's 'resumable'. AFL++ resumes natively. The surface-correct policy gate is re-applied inside — NO new gate. Returns the campaign dict; poll fuzz_status as before.",
     {"type": "object", "properties": {"campaign_id": {"type": "string"}}, "required": ["campaign_id"]}),
    ("run", "fuzz_verify_artifact", _t.verify_fuzz_artifact, "Replay a fuzz crash ARTIFACT byte-faithfully against its harness/binary and report whether it still crashes + the assurance rung — the first-class 'verify this crash reproducer' verb. The reproducer is materialized from CAS and mounted as a FILE (raw bytes preserved exactly — 0x00/0xff never text-mangled, unlike finding_verify_poc's stdin) and run against the campaign's preserved instrumented harness via the unforgeable `crash` oracle; a NETWORK crash re-sends its crashing message over the live socket + a liveness oracle. LLM-free; the surface-correct exec/egress gate is applied inside. Returns {verified, detail, assurance, output}. Prefer this to confirm a fuzz_crash finding still fires.",
     {"type": "object", "properties": {"artifact_id": {"type": "string"}}, "required": ["artifact_id"]}),
    ("run", "fuzz_minimize_artifact", _t.minimize_artifact, "Re-verify a crash artifact's reproducer (the crash→verify tie-in; an alias of fuzz_verify_artifact's replay path, kept for back-compat): replays its stored, CAS content-addressed minimized input against the target IN THE SANDBOX and checks the unforgeable `crash` oracle. LLM-free, gated by the existing exec policy; returns {verified, detail, assurance}. Prefer fuzz_verify_artifact (clearer name).",
     {"type": "object", "properties": {"artifact_id": {"type": "string"}}, "required": ["artifact_id"]}),

    # ---- net: live network interaction + egress audit -------------------------------
    ("read", "net_list_egress", _t.list_egress, "The egress audit log — every outbound network action (allowed/denied) the bounded-network tier recorded for the project. Review after any live testing to confirm you stayed in bounds.",
     {"type": "object", "properties": {"project_id": {"type": "string"}}, "required": ["project_id"]}),
    ("run", "net_http_request", _t.http_request, "Send ONE crafted HTTP request to a registered web surface and return {status,headers,body} (body capped at 64 KiB) — your hands for live web testing (log in, probe an auth check, fire an injection payload, read the response). body is form-encoded unless json_body=true. Pass `session` (any label) to keep a cookie jar across calls so an auth flow works (log in, then explore protected routes) — response lists the jar in session_cookies. Bounded, sandboxed, local-only egress, audited. Gated: features.network.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "method": {"type": "string", "description": "HTTP method"}, "path": {"type": "string"}, "params": {"type": "object"}, "headers": {"type": "object"}, "body": {"description": "request body (form-encoded unless json_body=true)"}, "json_body": {"type": "boolean"}, "session": {"type": "string", "description": "cookie-jar label to persist auth across calls"}}, "required": ["target_id", "method", "path"]}),
    ("run", "net_tcp_request", _t.tcp_request, "Talk to a raw TCP service on a live device (rehosted surface or remote target) — the non-HTTP net_http_request. Connect to the device's port (through the emulator netns when rehosted), optionally send `payload` bytes, read the bounded response; omit payload to banner-grab. Fingerprint a listening socket, or drive a binary-protocol bug — to PROVE one use finding_verify_poc with a tcp spec (it strips your sent bytes before matching). Bounded to the device host:port, audited. Gated: features.network.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "port": {"type": "integer"}, "payload": {"type": "string", "description": "bytes to send (omit to banner-grab)"}, "read_bytes": {"type": "integer"}}, "required": ["target_id", "port"]}),
    ("run", "net_udp_request", _t.udp_request, "Talk to a raw UDP service on a live device (rehosted surface or remote target) — the datagram analogue of net_tcp_request, for the firmware's UDP surface (infosvr/9999, SSDP/1900, mDNS/5353, DNS, DHCP, WS-Discovery). Send one datagram of `payload` bytes to the device's port (through the emulator netns when rehosted) and read the bounded response; omit payload to probe with an empty packet (UDP is connectionless — a silent service just yields no response). Fingerprint a listening udp socket, or drive a datagram-protocol bug — to PROVE one use finding_verify_poc with a udp spec (it strips your sent bytes before matching). Bounded to the device host:port, audited. Gated: features.network.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "port": {"type": "integer"}, "payload": {"type": "string", "description": "bytes to send (omit to probe with an empty packet)"}, "read_bytes": {"type": "integer"}}, "required": ["target_id", "port"]}),
    ("run", "net_remote_list_files", _t.remote_list_files, "Enumerate files on a live remote target (SSH/telnet) under `path` (bounded depth/count) — fs_list for a box you don't have firmware for. Read-only. Gated: features.remote.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "path": {"type": "string"}, "max_depth": {"type": "integer"}, "max_entries": {"type": "integer"}}, "required": ["target_id"]}),
    ("run", "net_remote_read_file", _t.remote_read_file, "Read ONE file from a live remote target (bounded; text as-is, binary as hex) — configs/scripts/keys//etc/passwd. The device's own bytes, read-only. Gated: features.remote.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "path": {"type": "string"}, "max_bytes": {"type": "integer"}}, "required": ["target_id", "path"]}),
    ("run", "net_remote_run", _t.remote_run, "Run ONE allowlisted READ-ONLY recon tool on a live remote target. No arbitrary shell (a path for ls is shell-quoted). Same recon we'd run on a rehosted rootfs. Gated: features.remote.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "tool": {"type": "string", "enum": REMOTE_TOOLS, "description": "the read-only recon tool to run"}, "path": {"type": "string", "description": "argument for ls (shell-quoted)"}}, "required": ["target_id", "tool"]}),
    ("run", "net_remote_launch", _t.remote_launch, "Start a service on a live remote/rehosted device that didn't auto-start, by BINARY PATH (+ optional args), backgrounded — so its socket comes up for live testing (e.g. a rehosted firmware's vulnerable daemon). path + args are shell-quoted; the one non-read-only remote op (no arbitrary shell). Then reach it with net_tcp_request / finding_verify_poc (tcp spec). Gated: features.remote.",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "path": {"type": "string"}, "args": {"type": "array", "items": {"type": "string"}}}, "required": ["target_id", "path"]}),

    # ---- task: the task runner ------------------------------------------------------
    ("run", "task_run", _t.run_task, "Run a HexGraph analysis task on a target and return its findings. `type` selects the task: recon (sandbox recon), static_analysis (GROUNDED P-Code source→sink taint + LLM synthesis), reverse_engineering / pattern_sweep (LLM-driven), harness_generation (auto-build a fuzz harness), fuzzing (a quick fuzz pass — prefer fuzz_start for campaigns), poc (verify exploitation), surface_recon (offline route→handler map from a supplied spec), web_discover (LIVE crawl that DISCOVERS routes/params from links+forms+common paths — use on a rehosted/registered surface, needs features.network), web_recon (live liveness probe, needs features.network).",
     {"type": "object", "properties": {"target_id": {"type": "string"}, "type": {"type": "string", "enum": TASK_TYPES, "description": "the task type to run"}, "objective": {"type": "string", "description": "optional free-form objective to steer an LLM task"}, "params": {"type": "object", "description": "task-specific params (e.g. a surface route spec, target_sources, seeds)"}}, "required": ["target_id", "type"]}),

    # ---- meta: schemas + health -----------------------------------------------------
    ("read", "meta_get_schemas", _t.get_schemas, "The write-API contract: allowed enums, the Finding shape, per-type NODE attribute schemas (what to populate, the sink-vs-symbol rule), edge/socket attribute schemas, the finding_verify_poc oracle specs, and the active decompiler (with a health flag). Call this FIRST to learn the object model, and before finding_record/graph_create_node/graph_create_edge/graph_annotate to avoid guessing.",
     {"type": "object", "properties": {}}),
    ("read", "meta_check_decompiler", _t.check_decompiler, "Verify the decompiler re_decompile_function/re_disassemble use ACTUALLY works (not merely the configured name) — radare2 needs the sandbox image up; Ghidra (headless) needs WITH_GHIDRA=1 in the image, Ghidra (bridge) needs a reachable server. Returns {active, working, mode, version, detail} with an ACTIONABLE detail when broken. Run this if a re_decompile_function fails or before relying on Ghidra, so you don't burn turns against a broken backend.",
     {"type": "object", "properties": {}}),
    ("read", "meta_check_features", _t.check_features, "Preflight the features whose RUNTIME dependency can diverge from what's configured (floss, yara, angr, ghidra/emulation) — so you can tell 'configured but BROKEN' from ready BEFORE spending a run. Each feature returns a `state`: `available` (its dep/image is present), `broken` (the dep/image is MISSING — the stale-sandbox-image trap) with an ACTIONABLE `remediation` (e.g. `just sandbox-build`, `just angr-build`), or `disabled` (only for the GATED features angr + ghidra/emulation, when their features.X gate is off). The always-on static tools floss + yara have no gate, so they report availability only (available or broken). Also returns `image_stale` (tri-state) — a PROACTIVE hint that the sandbox image PREDATES docker/sandbox.Dockerfile (so it may silently lack newer tools even when the per-feature probes pass); rebuild with `just sandbox-build`. The check is LIGHTWEIGHT (a tiny in-image dep probe, --network none, no analysis) and read-only. Also returns `gates` — the POLICY gates (PoC/fuzzing execution, network egress, rehost, live-remote) with each one's enabled state + the policy tier it raises — so a firmware proving run can preflight which exec/egress tiers are open instead of hitting a refusal mid-run. Run this in your orient step, alongside meta_check_decompiler, before reaching for floss/yara, an opt-in tool (re_solve_reaching_input), or a proving/fuzzing run, so you don't burn turns against a broken feature or a gated-off tier.",
     {"type": "object", "properties": {}}),
]


# Tools advertised ONLY when their opt-in feature is enabled (vs. the always-on verbs that
# just return an "enable X" message when used while off). Keeping these OUT of the list until
# the user opts in keeps the agent's context lean. Each entry maps a tool name to a predicate
# read at catalog-build time. FLOSS + YARA are NOT here — they relax no policy boundary and
# ride the static surface ungated (like binutils), so they are always advertised.
def _solver_advertised() -> bool:
    # angr IS a policy gate (policy.assert_allows_solver) but, like emulation, it raises no tier,
    # so the advertisement reads the plain feature flag.
    try:
        from hexgraph.engine.re.solver import solver_enabled

        return solver_enabled()
    except Exception:  # noqa: BLE001 — never advertise a tool whose gate can't be read
        return False


_FEATURE_GATED_TOOLS = {
    "re_solve_reaching_input": _solver_advertised,
    "re_solve_constraint": _solver_advertised,
}


def catalog(enabled_groups: set[str] | None = None) -> list[dict]:
    """Tool specs for the MCP server, filtered to the enabled groups (default: all) and to the
    opt-in feature gates (a feature-gated tool like re_solve_reaching_input is advertised only
    when its feature is enabled). Trimming groups keeps the agent's tool list small when only
    part of HexGraph is wanted (e.g. write-only, to populate the graph from a UI-driven session)."""
    groups = set(GROUPS) if enabled_groups is None else enabled_groups
    return [
        {"group": g, "name": n, "fn": fn, "description": d, "schema": sch}
        for (g, n, fn, d, sch) in _CATALOG
        if g in groups and _FEATURE_GATED_TOOLS.get(n, lambda: True)()
    ]
