"""observation and enrichment_fact tables (Phase O)

Revision ID: 0017_observation_store
Revises: 0016_build_supplychain_source_revision
Create Date: 2026-06-04 20:50:58.284194
"""
from alembic import op
import sqlalchemy as sa


revision = '0017_observation_store'
down_revision = '0016_build_supplychain_source_revision'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_fact',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('subject_kind', sa.String(length=16), nullable=False),
    sa.Column('subject_key', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=40), nullable=False),
    sa.Column('fact_kind', sa.String(length=40), nullable=False),
    sa.Column('fact_json', sa.JSON(), nullable=False),
    sa.Column('source_observation_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichment_fact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrichment_fact_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_enrichment_fact_subject', ['target_id', 'node_type', 'subject_kind', 'subject_key'], unique=False)

    op.create_table('observation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('args_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('result_kind', sa.String(length=40), nullable=False),
    sa.Column('result_cas', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('node_refs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observation_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_result_kind'), ['result_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_tool'), ['tool'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_tool'))
        batch_op.drop_index(batch_op.f('ix_observation_target_id'))
        batch_op.drop_index(batch_op.f('ix_observation_result_kind'))
        batch_op.drop_index(batch_op.f('ix_observation_project_id'))
        batch_op.drop_index(batch_op.f('ix_observation_content_hash'))

    op.drop_table('observation')
    with op.batch_alter_table('enrichment_fact', schema=None) as batch_op:
        batch_op.drop_index('ix_enrichment_fact_subject')
        batch_op.drop_index(batch_op.f('ix_enrichment_fact_project_id'))

    op.drop_table('enrichment_fact')
    # ### end Alembic commands ###
