"""add cwe envelope field to finding

Revision ID: a0e618f6088f
Revises: 0017_observation_store
Create Date: 2026-06-07 11:56:30.144976
"""
from alembic import op
import sqlalchemy as sa


revision = '0018_finding_cwe'
down_revision = '0017_observation_store'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cwe', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_finding_cwe'), ['cwe'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_cwe'))
        batch_op.drop_column('cwe')

    # ### end Alembic commands ###
