"""journal_entry and journal_mention tables (working-memory layer)

Revision ID: 0019_journal
Revises: 0018_finding_cwe
Create Date: 2026-06-07 19:22:17.531527
"""
from alembic import op
import sqlalchemy as sa


revision = '0019_journal'
down_revision = '0018_finding_cwe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_mention',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('ref_kind', sa.String(length=16), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_mention', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_mention_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index('ix_journal_mention_ref', ['ref_kind', 'ref_id'], unique=False)

    op.create_table('journal_entry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('author', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('origin_task_id', sa.String(length=36), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_origin_task_id'), ['origin_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_project_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_origin_task_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_author'))

    op.drop_table('journal_entry')
    with op.batch_alter_table('journal_mention', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_mention_ref')
        batch_op.drop_index(batch_op.f('ix_journal_mention_entry_id'))

    op.drop_table('journal_mention')
    # ### end Alembic commands ###
