"""index finding and task target_id for merge scans

Revision ID: 3a6f3dd519ff
Revises: 95bb894a0ef6
Create Date: 2026-07-24 14:29:52.121563
"""
from alembic import op
import sqlalchemy as sa


revision = '3a6f3dd519ff'
down_revision = '95bb894a0ef6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_target_id'), ['target_id'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_target_id'), ['target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_target_id'))

    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_target_id'))

    # ### end Alembic commands ###
