"""baseline

Revision ID: bbdb1d98bf54
Revises: 
Create Date: 2026-05-30 16:59:32.052719
"""
from alembic import op
import sqlalchemy as sa


revision = 'bbdb1d98bf54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('suggested_followups_json', sa.JSON(), nullable=False),
    sa.Column('related_target_refs_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('new', 'accepted', 'dismissed', name='findingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('llm_backend', sa.Enum('mock', 'anthropic', 'claude_code', name='llmbackendname'), nullable=False),
    sa.Column('model_pref', sa.String(length=100), nullable=True),
    sa.Column('data_dir', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('objective_text', sa.Text(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'needs_triage', name='taskstatus'), nullable=False),
    sa.Column('backend', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_path', sa.Text(), nullable=True),
    sa.Column('parent_finding_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_finding_id'], ['finding.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('firmware_image', 'executable', 'shared_library', 'unknown', name='targetkind'), nullable=False),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('arch', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['target.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edge',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('src_target_id', sa.String(length=36), nullable=False),
    sa.Column('dst_target_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('contains', 'links_against', 'related_to', name='edgetype'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dst_target_id'], ['target.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['src_target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edge')
    op.drop_table('target')
    op.drop_table('task')
    op.drop_table('project')
    op.drop_table('finding')
    # ### end Alembic commands ###
